version: '2.29'

services:
  backend:
    build:
      context: sw-code-BE
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:8080"  # на фичах 8080 занят, поэтому прокидываем 3001
    networks:
      - app-network

  frontend:
    build:
      context: sw-code-FE
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"  # Отображаем 3000 порт локально и внутри контейнера
    networks:
      - app-network
    depends_on:
      - backend
      
  nginx:
    image: nginx:latest
    container_name: sw-code-nginx
    ports:
      - "4000:80"  # Nginx доступен на 80 порту
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Монтируем наш nginx.conf
    networks:
      - app-network
    depends_on: 
      - frontend
    

networks:
  app-network:
    driver: bridge
