version: '3.8'

services:
  backend:
    build:
      context: sw-code-BE
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"  # Отображаем 8080 порт локально и внутри контейнера
    networks:
      - app-network

  frontend:
    build:
      context: sw-code-FE
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"  # Отображаем 3000 порт локально и внутри контейнера
    networks:
      - app-network
    depends_on:
      - backend
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Nginx доступен на 80 порту
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Монтируем наш nginx.conf
    networks:
      - app-network
    depends_on: 
      - frontend
    

networks:
  app-network:
    driver: bridge