name: fe-checkout

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  lint:
    runs-on: ${{ matrix.os }} 

    strategy:
      matrix:
        node-version: [18, 20] 
        os: [ubuntu-latest] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable corepack and activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Alpine dependencies
        if: matrix.os == 'alpine'
        run: |
          apk add --no-cache curl bash

      - name: Install dependencies
        run: pnpm install
        working-directory: ./sw-code-FE 

      - name: Run lint
        run: pnpm lint
        working-directory: ./sw-code-FE  